# -*- coding: utf-8 -*-
"""weekly_merging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WbNVveCUnbE8Bx7pgnq4HXjFasg7X3BT
"""

from google.colab import drive
drive.mount('/content/gdrive')
nbdir = "/content/gdrive/My Drive/DSCI511/Colab/data/"

import glob
import pandas as pd

filepath = '/content/gdrive/My Drive/DSCI511/Colab/data/project/'
files = glob.glob(filepath + "/*.csv")

d_list = []

for f in files:
    df = pd.read_csv(f, index_col=None, header=0)
    d_list.append(df)


merged_df = pd.concat(d_list).drop_duplicates().reset_index(drop=True)
merged_df.head()

from datetime import date
today = date.today().strftime('%Y-%m-%d')
today = str(today.replace('-', ''))

filepath = '/content/gdrive/My Drive/DSCI511/Colab/data/project/all_data/' + str(today) + 'all_data.csv'
merged_df.to_csv(filepath, index = False)